#!/bin/bash
# INA219 Connection Fix Script

echo "=========================================="
echo "INA219 CONNECTION FIX"
echo "=========================================="
echo ""
echo "⚠️  CRITICAL: You connected 5V to VCC!"
echo ""
echo "The Jetson Orin Nano I2C operates at 3.3V logic level."
echo "Even though the SOLDERED INA219 has a voltage regulator,"
echo "the I2C lines (SDA/SCL) MUST be 3.3V compatible."
echo ""
echo "=========================================="
echo "CORRECT CONNECTIONS:"
echo "=========================================="
echo ""
echo "Jetson Pin → INA219 Pin"
echo "------------------------"
echo "Pin 1 (3.3V)  → VCC    ⚠️  USE 3.3V, NOT 5V!"
echo "Pin 6 (GND)   → GND"
echo "Pin 27 (SDA)  → SDA"
echo "Pin 28 (SCL)  → SCL"
echo ""
echo "Power Monitoring:"
echo "Battery +     → IN+"
echo "Battery - (through load) → IN-"
echo ""
echo "=========================================="
echo "AFTER FIXING CONNECTIONS, RUN:"
echo "=========================================="
echo ""
echo "1. Check if INA219 appears on bus 0:"
echo "   sudo i2cdetect -y -r 0"
echo ""
echo "2. Run diagnostic:"
echo "   python3 diagnose_ina219.py"
echo ""
echo "3. Test monitoring:"
echo "   python3 test_ina219.py"
echo ""
echo "=========================================="
